version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - categoria
  - ekoru
  - Ekoru
  - nestjs
  - subcategoria
  - subcategoría
  - Subcategoría
  - subcategorías
ignoreWords: []
import: []
